# blendshape -> au 매핑
BLENDSHAPE_CONFIG = {
    "jawForward": ("AU29", "턱을 앞으로 내밈"),
    "jawLeft": ("AU30", "턱을 옆으로 움직임_왼"),
    "jawRight": ("AU30", "턱을 옆으로 움직임_오"),
    "jawOpen": ("AU26", "입 벌림"),
    "mouthFunnel": ("AU22", "입 모양을 오므림"),
    "mouthPucker": ("AU18", "입술 오므림"),
    "mouthSmileLeft": ("AU12", "웃음_왼"),
    "mouthSmileRight": ("AU12", "웃음_오"),
    "mouthFrownLeft": ("AU15", "입꼬리 내림_왼"),
    "mouthFrownRight": ("AU15", "입꼬리 내림_오"),
    "mouthDimpleLeft": ("AU14", "입 양옆 당김_왼"),
    "mouthDimpleRight": ("AU14", "입 양옆 당김_오"),
    "mouthStretchLeft": ("AU20", "입 좌우로 당김_왼"),
    "mouthStretchRight": ("AU20", "입 좌우로 당김_오"),
    "mouthRollLower": ("AU28", "아래 입술 말림"),
    "mouthRollUpper": ("AU28", "위 입술 말림"),
    "mouthShrugLower": ("AU17", "턱 올림"),
    "mouthShrugUpper": ("AU17", "턱 올림"),
    "mouthPressLeft": ("AU24", "입술 압박_왼"),
    "mouthPressRight": ("AU24", "입술 압박_오"),
    "mouthLowerDownLeft": ("AU16", "아래 입술 내림_왼"),
    "mouthLowerDownRight": ("AU16", "아래 입술 내림_오"),
    "mouthUpperUpLeft": ("AU10", "위 입술 들림_왼"),
    "mouthUpperUpRight": ("AU10", "위 입술 들림_오"),
    "cheekPuff": ("AU34", "볼 부풀림"),
    "cheekSquintLeft": ("AU6", "눈가 주름_왼"),
    "cheekSquintRight": ("AU6", "눈가 주름_오"),
    "noseSneerLeft": ("AU9", "콧날 들림_왼"),
    "noseSneerRight": ("AU9", "콧날 들림_오")
}